### ISSUE TITLE
Untested MacOS support

### ISSUE THREAD

**Issue by krOoze** [krOoze/Hello_Triangle#3]
I have no way to test MacOS support. But theoretically GLFW should be able to handle it. I would be grateful if someone tests it.

**Comment by ChanLee1123** [comment]
![image](https://user-images.githubusercontent.com/48939360/81035698-13d41380-8ed7-11ea-8ae7-513d4126763a.png)
Hi krOoze. I cloned this repository and build it with cmake.
And It works well. Do you have anything more to test?

To set configuration for vulkan in mac os, It will be good for you to refer to this link:
https://vulkan.lunarg.com/doc/view/1.0.69.0/mac/getting_started.html

Because the vulkan sdk is not set automatically on the environment variable in the mac os.
If you don't do this, the cmake will complain. So you should do it by `export` command. 

And also Don't forget to set the Validation Layer json file locations.

**Comment by krOoze** [comment]
Thanks! ❤️ 

Didn't even expect it to just work just like that 😅 

The platform differences are annoying. Yea I prefer to rely on `VULKAN_SDK` variable. (Same as on linux) this is done by the `setup-env.sh`, as the SDK docs say. Though it means my Cmake fails for other installation methods...

> Do you have anything more to test?

Nah, that's mostly all. I just need it to run. It should survive resizing, minimization, maximization, and fullscreen without crashes or any weirdness. For bonus points you could try different present mode at https://github.com/krOoze/Hello_Triangle/blob/5528dbbd3f79542a5fb2b225b47858f8a8f01b7a/src/HelloTriangle.cpp#L76

**Comment by ChanLee1123** [comment]
My mac spec is 

Processor : Quad-Core Intel Core i5
Graphics : Radeon Pro 570
OS : macOS Catalina 10.15.3

In my machine with all of present modes such as `IMMEDIATE`, `FIFO`, `MAILBOX`, All of cases such as resizing, minimization, maximization, and fullscreen does not cause any errors or crashes. 

The application is stable in my machine!

**Comment by krOoze** [comment]
Thanks again @ChanLee1123. I very much appreciate the help.
