### ISSUE TITLE
DXGI based swapchain wrapper

### ISSUE THREAD

**Issue by Zingam** [krOoze/Hello_Triangle#8]
This is a follow-up question to https://github.com/KhronosGroup/Vulkan-Docs/issues/366#issuecomment-667127418

I decided to start from scratch. My new effort will be to UWP/DX12 on the Windows based platforms and Vulkan for non-Mac platforms, eventually Metal on Mac. I'll forgo SDL2 or any other libraries and do everything natively. In that context I want to forgo doing a Win32 application. Is DXGI feasible enough to share the DX12 code with a Vulkan renderer even if it is just for development purposes to save time on redoing the same stuff with a different API? DXGI should be enough to enumerate monitors, screens, setup windows etc. I guess.

Windows/MSVC is my primary development platform and the targets are UWP/Xbox, Android, Apple.

**Comment by krOoze** [comment]
I did not really explore this past what you can see at the dirty experiment in the [dxgi_interop](https://github.com/krOoze/Hello_Triangle/blob/dxgi_interop/src/WSI/DxgiWsi.h) branch.

Probably OK for development purposes, but it is brittle. What I understood from the MS docs is that swapchain images cannot be created `DXGI_USAGE_SHARED`, but it seems to work anyway. For your usecase it might be better to export regular `VkImage` to DX, and then copy it into the DX swapchain, which should work without any dirty tricks.

Also I have not tested `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT`, which would probably be the modern way to do things. Furthermore, I still use win32 HWND, and have not tested actual UWP window surface (via `CreateSwapChainForComposition()`). And obviously none of this would work on the Xbox, since I assume there's no Vulkan in the first place.

**Comment by Zingam** [comment]
Thank you for the advice. `VkImage` sounds like the best option to explore.
